Feat customizable commands
aziontech/azion-cli pull request #257
Opened 2023-01-06 13:19 UTC by MaxwelMazur

- customizable command for all points

2023-01-06 13:33 UTC, PatrickMenoti requested changes

2023-01-06 13:33 UTC, PatrickMenoti commented on pkg/cmd/webapp/build/build.go
> +        command = conf.BuildData.Default
default should always run 
cmd is the custom command

2023-01-06 19:20 UTC, PatrickMenoti requested changes

2023-01-06 19:20 UTC, PatrickMenoti commented on pkg/cmd/webapp/publish/publish.go
> +        fmt.Println(">>> err: ", err)
I think you forgot to remove this

2023-01-09 19:58 UTC, MaxwelMazur commented on pkg/cmd/webapp/publish/publish.go
> +        fmt.Println(">>> err: ", err)
removed

2023-01-09 20:18 UTC, PatrickMenoti approved these changes
lgtm

2023-01-09 20:25 UTC, pauloSF0 approved these changes

2023-01-09 20:26 UTC, merged