feat: describe domains
aziontech/azion-cli pull request #276
Opened 2023-01-24 18:55 UTC by MaxwelMazur

- describe domains 
- testing unit

2023-01-24 19:05 UTC, PatrickMenoti requested changes

2023-01-24 19:05 UTC, PatrickMenoti commented on messages/domains/errors.go
> +	DomainsFlagId      = "Unique identifier of the Edge Application"
Domain

2023-01-24 19:40 UTC, MaxwelMazur commented on messages/domains/errors.go
> +	ErrorMissingApplicationIdArgument = errors.New("A mandatory flag is missing. You must provide an domain_id as an argument or path to import the file. Run the command 'azioncli domains <subcommand> -
I did not understand, explain better

2023-01-24 20:42 UTC, PatrickMenoti approved these changes

2023-01-25 12:48 UTC, PatrickMenoti approved these changes

2023-01-25 13:32 UTC, merged