Feat: create update command
aziontech/azion-cli pull request #298
Opened 2023-02-13 19:29 UTC by MaxwelMazur

- update command created

2023-02-14 12:39 UTC, PatrickMenoti requested changes

2023-02-14 12:39 UTC, PatrickMenoti commented on pkg/cmd/origins/update/update.go
> +        $ azioncli origins update --application-id 1673635839 --origin-key "58755fef-e830-4ea4-b9e0-6481f1ef496d" --in "update.json"
when --in is sent, we should ignore all the other flags, so you can remove that from the example

2023-02-14 12:39 UTC, PatrickMenoti commented on pkg/cmd/origins/update/update.go
> +				if !cmd.Flags().Changed("application-id") || !cmd.Flags().Changed("origin-key") ||
I think only application_id and origin-key are mandatory in update, right? OR you actually have to resend fields you don't want to update??

2023-02-14 20:50 UTC, PatrickMenoti approved these changes
LGTM

2023-02-15 11:37 UTC, gabriel-azion approved these changes

2023-02-15 12:52 UTC, merged