feat: create delete command
aziontech/azion-cli pull request #299
Opened 2023-02-13 20:56 UTC by MaxwelMazur

- update command created
- unit test

2023-02-14 12:33 UTC, PatrickMenoti requested changes

2023-02-14 12:33 UTC, PatrickMenoti commented on pkg/cmd/origins/delete/delete.go
> +		  $ azioncli origins delete --application-id 1234 --cascade
cascade delete only happens in edge_application delete command

2023-02-14 20:49 UTC, PatrickMenoti approved these changes

2023-02-15 11:39 UTC, gabriel-azion approved these changes

2023-02-15 12:40 UTC, merged