ENG-24098-create-origins-messages-errors
aziontech/azion-cli pull request #301
Opened 2023-02-15 13:54 UTC by gabriel-azion

Origins: 
- errors
- messages

2023-02-15 13:59 UTC, PatrickMenoti requested changes

2023-02-15 13:59 UTC, PatrickMenoti commented on messages/origins/errors.go
> +	ErrorMissingArguments             = errors.New("Required flags are missing. You must supply application-id and origin-id as arguments. Run 'azioncli <command> <subcommand> --help' command to display
We will have to update all messages with this new standard (future PRs)

2023-02-15 13:59 UTC, PatrickMenoti commented on messages/origins/errors.go
> +	ErrorMandatoryUpdateFlags         = errors.New("Mandatory flags are missing. You must provide application-id and origin-id flags when the --application-id and --in flag are not provided. Run the com
Should be either required or mandatory

2023-02-15 14:00 UTC, gabriel-azion commented on messages/origins/errors.go
> +	ErrorMandatoryUpdateFlags         = errors.New("Mandatory flags are missing. You must provide application-id and origin-id flags when the --application-id and --in flag are not provided. Run the com
agreed

2023-02-15 14:02 UTC, gabriel-azion commented on messages/origins/errors.go
> +	ErrorMandatoryUpdateFlags         = errors.New("Mandatory flags are missing. You must provide application-id and origin-id flags when the --application-id and --in flag are not provided. Run the com
done @PatrickMenoti

2023-02-15 14:10 UTC, gabriel-azion commented
I have read the CLA Document and I hereby sign the CLA

2023-02-15 19:39 UTC, PatrickMenoti commented on messages/origins/messages.go
> +	OriginsUpdateFlagOriginPath           = "Gives a file path to the origin"
Origin Path from RTM: Azion can request your content from a directory in your origin. Azion appends Origin Path to the URI when forwarding the request to your origin. Leave it in blank to use only the URI.

2023-02-16 14:32 UTC, PatrickMenoti approved these changes
LGTM

2023-02-16 15:42 UTC, merged