feat: update command for edge functions instances
aziontech/azion-cli pull request #348
Opened 2023-04-11 20:33 UTC by PatrickMenoti

**WHAT**
- Update command for edge functions instances;
- Unit tests.

2023-04-11 21:02 UTC, pauloSF0 approved these changes

2023-04-12 09:49 UTC, MaxwelMazur requested changes

2023-04-12 14:00 UTC, PatrickMenoti commented on pkg/api/edge_applications/edge_applications.go
> +		fmt.Println(httpResp.Body)
oops

2023-04-12 14:26 UTC, MaxwelMazur approved these changes
Lgtm

2023-04-12 18:23 UTC, merged